/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}", // CRITICAL: Vite checks these files
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#2f4c59",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#00468b",
        "tertiary-fixed": "#c9e7f7",
        "primary-fixed-dim": "#a8c8ff",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "on-tertiary-fixed": "#001f2a",
        "on-tertiary-fixed-variant": "#2e4b57",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "outline-variant": "#c2c6d4",
        "primary": "#00488d",
        "surface-tint": "#005db5",
        "on-primary-fixed": "#001b3d",
        "surface-variant": "#e1e3e4",
        "background": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#476471",
        "secondary": "#006a60",
        "on-primary": "#ffffff",
        "secondary-fixed": "#85f6e5",
        "on-primary-container": "#cadcff",
        "on-secondary-fixed": "#00201c",
        "primary-fixed": "#d6e3ff",
        "on-surface": "#191c1d",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#67d9c9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005048",
        "inverse-primary": "#a8c8ff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#c1e0ef",
        "primary-container": "#005fb8",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#adcbda",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "outline": "#727783",
        "on-error": "#ffffff",
        "on-surface-variant": "#424752",
        "on-secondary-container": "#007166"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "md": "16px",
        "xl": "32px",
        "gutter": "16px",
        "sm": "8px",
        "margin-mobile": "16px",
        "base": "8px",
        "lg": "24px",
        "margin-desktop": "32px"
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "0px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "0px", "fontWeight": "600"}],
        "display-lg": ["57px", {"lineHeight": "64px", "letterSpacing": "-0.25px", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.5px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0.5px", "fontWeight": "400"}],
        "title-lg": ["22px", {"lineHeight": "28px", "letterSpacing": "0px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.25px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}